#! /usr/bin/perl -w

# Need some thought on when the templates should be expanded and when the action should be called.

use esmith::Build::CreateLinks qw(:all);
# my $event = "rocketchat-update";
# rocketchat-update

foreach (qw(
       /etc/rc.d/init.d/rocketchat
       /etc/profile.d/scls-rh-mongodb26.sh
       /etc/profile.d/scls-rh-python34.sh
       /etc/profile.d/scls-rh-java-common.sh
       /etc/opt/rh/rh-mongodb26/mongod.conf
       ))

{
    templates2events("$_", qw(
    post-upgrade
    console-save
    bootstrap-console-save
    remoteaccess-update
    ));
}

# Runlevel init links.
service_link_enhanced("rocketchat", "S99", "7");

# Must be an easier way....
service_link_enhanced("rocketchat", "K01", "0");
service_link_enhanced("rocketchat", "K01", "1");
service_link_enhanced("rocketchat", "K01", "2");
service_link_enhanced("rocketchat", "K01", "3");
service_link_enhanced("rocketchat", "K01", "4");
service_link_enhanced("rocketchat", "K01", "5");
service_link_enhanced("rocketchat", "K01", "6");


# Set up generic logfile timestamp renaming/symlinking

foreach (qw(
    /var/log/rocketchat.log
    ))
{
    safe_touch "root/etc/e-smith/events/logrotate/logfiles2timestamp/$_";
}

#--------------------------------------------------
# actions for logrotate event
#--------------------------------------------------

#$event = "logrotate";

#safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/ipsec");
