#! /usr/bin/perl -w

# Need some thought on when the templates should be expanded and when the action should be called.

use esmith::Build::CreateLinks qw(:all);
# my $event = "rocketchat-update";
# rocketchat-update

foreach (qw(
       /etc/rc.d/init.d/rocketchat
       /etc/profile.d/scls-rh-mongodb26.sh
       /etc/profile.d/scls-rh-python34.sh
       /etc/profile.d/scls-rh-java-common.sh
       /etc/opt/rh/rh-mongodb26/mongod.conf
       ))

{
    templates2events("$_", qw(
    post-upgrade
    console-save
    bootstrap-console-save
    remoteaccess-update
    ));
}

# Runlevel init links.
service_link_enhanced("rocketchat", "S99", "7");
service_link_enhanced("rocketchat", "K01", "6");
service_link_enhanced("rocketchat", "K01", "0");
service_link_enhanced("rocketchat", "K01", "1");

# I think the following are unnecessary as the mongo RPM adds its own links
# 
#service_link_enhanced("rh-mongodb26-mongod", "S98", "7");
#service_link_enhanced("rh-mongodb26-mongod", "K21", "6");
#service_link_enhanced("rh-mongodb26-mongod", "K21", "0");
#service_link_enhanced("rh-mongodb26-mongod", "K21", "1");

# Set up generic logfile timestamp renaming/symlinking

foreach (qw(
    /var/log/pluto/rocketchat.log
    ))
{
    safe_touch "root/etc/e-smith/events/logrotate/logfiles2timestamp/$_";
}

#--------------------------------------------------
# actions for logrotate event
#--------------------------------------------------

#$event = "logrotate";

#safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/ipsec");
