#!/bin/bash

#
#	/etc/rc.d/init.d/rocketchat
#
#	rocketchat - Provisioned using forever-service
#
# chkconfig: 2345 90 10 
# description: forever-service startup script for node script based service rocketchat, uses forever to start the service
#
#	CLI node /usr/local/bin/forever-service install -s main.js -e ROOT_URL=https://test.reetspetit.info/ MONGO_URL=mongodb://localhost:27017/rocketchat PORT=3000 MAIL_URL=smtp://reetspetit.info:25 -p /opt/rh/nodejs010/root/usr/lib/node_modules/forever/bin rocketchat
#	Working Directory /opt/Rocket.Chat

#Setup Environment variables (if any)
